### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by J-Cook-jr** [dappforce/subsocial-node#99]
Hi, I'm getting this error after running  cargo build --release. Can you help me solve this issue? Thanks!

<img width="1280" alt="Screen Shot 2021-04-05 at 1 44 28 PM" src="https://user-images.githubusercontent.com/62865359/113606266-c6e04c00-9615-11eb-849b-778d030f7494.png">

**Comment by F3Joule** [comment]
```
rustup update nightly-2020-07-02
rustup target add wasm32-unknown-unknown --toolchain nightly-2020-07-02
```
Then run cargo commands win `+nightly-2020-07-02` or just run one-time command `rustup override set nightly-2020-07-02`.
This should help with this compiler errors.

**Comment by TomaszWaszczyk** [comment]
@J-Cook-jr try to execute before compiling file `init.sh` in `script` directory.

**Comment by F3Joule** [comment]
> @J-Cook-jr try to execute before compiling file `init.sh` in `script` directory.

Not sure that `scripts/init.sh` is ok on the branch which @J-Cook-jr used to compile.
Furthermore, on the current master there's `rust-toolchain` file, which specifies version to use to compile.
Your suggestion is ok after #108 will be merged. Toolchain file is going to be removed (because of srtool conflict) and all configurations will go to init.sh

**Comment by siman** [comment]
Should be fixed by this PR: https://github.com/dappforce/subsocial-node/pull/108
